export const MISSING_PLAYER_DATA_TO_INITIALIZE = 'Certaines informations sont manquantes pour créer le joueur';
export const NO_LOCAL_PLAYER = "Aucun joueur local n'a encore été défini";
export const INVALID_PAYLOAD_FOR_ACTION_TYPE = 'Payload invalide pour ce type de commande';
export const NO_CURRENT_ROUND = "Aucune round n'est active présentement";
export const NO_START_GAME_TIME = "La partie n'et pas encore commencée, alors il n'y a pas encore de temps de départ";
export const SOCKET_ID_UNDEFINED = "L'identifiant du socket n'est pas défini";
export const INVALID_ROUND_DATA_PLAYER = 'Impossible de convertir le round data avec ce joueur';
export const EXPIRED_COOKIE_AGE = '-99999999';
export const NO_SUBJECT_FOR_EVENT = 'There is no subject for the event requested';
export const IS_NOT_BEHAVIOR_OBJECT = 'Subject is not BehaviorSubject and therefore does not have value';
export const PLAYER_NUMBER_INVALID = (playerNumber: number) => `There is no player ${playerNumber} in the game`;
